name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  # build-and-push:
  #   name: Build and Push Docker Image
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: docker.io/axoloot/portfolio:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    # needs: build-and-push

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem && cat private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            docker pull docker.io/axoloot/portfolio:latest &&
            docker stop portfolio ||
            true && docker rm portfolio ||
            true &&
            docker run -d -p 80:80 --name portfolio docker.io/axoloot/portfolio:latest
          '
