name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Commit SHAs
        id: commit_shas
        run: |
          CURRENT_SHA=$(git rev-parse --short HEAD)
          PREVIOUS_SHA=$(git rev-list --skip=1 -n 1 HEAD)
          OLDER_SHA=$(git rev-list --skip=2 -n 1 HEAD)
          echo "::set-output name=current_sha::$CURRENT_SHA"
          echo "::set-output name=previous_sha::$PREVIOUS_SHA"
          echo "::set-output name=older_sha::$OLDER_SHA"

      - name: Pull current latest image
        run: |
          docker pull docker.io/axoloot/portfolio:latest || true

      - name: Tag current latest with previous commit SHA
        if: success() && steps.commit_shas.outputs.previous_sha != ''
        run: |
          docker tag docker.io/axoloot/portfolio:latest docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.previous_sha }}

      - name: Push current latest with previous commit SHA
        if: success() && steps.commit_shas.outputs.previous_sha != ''
        run: |
          docker push docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.previous_sha }}

      - name: Pull previous commit SHA image
        run: |
          docker pull docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.previous_sha }} || true

      - name: Tag previous commit SHA image with older commit SHA
        if: success() && steps.commit_shas.outputs.older_sha != ''
        run: |
          docker tag docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.previous_sha }} docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.older_sha }}

      - name: Push previous commit SHA image with older commit SHA
        if: success() && steps.commit_shas.outputs.older_sha != ''
        run: |
          docker push docker.io/axoloot/portfolio:${{ steps.commit_shas.outputs.older_sha }}

      - name: Build and Tag New Docker Image as Latest
        run: |
          docker build -t docker.io/axoloot/portfolio:latest .

      - name: Push New Docker Image as Latest
        run: |
          docker push docker.io/axoloot/portfolio:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST }}
            USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            docker pull docker.io/axoloot/portfolio:latest &&
            docker stop portfolio || true &&
            docker rm portfolio || true &&
            docker run -d -v /home/ubuntu/certs/:/tmp/certs -p 80:80 -p 443:443 --name portfolio docker.io/axoloot/portfolio:latest
          '
